url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

title: Mother Karaoke
description: A searchable index of karaoke songs for Mother in Atlanta, GA.
logo:
#social:
  #links:
    #- Uncomment and put social links here

exclude: ["_assets", "gulp", ".gitignore", "gulpfile.js", "package.json", "node_modules", "README.md", "Gemfile"]
keep_files: ["assets"]

# collections

# defaults

# gems
